# Generated by Django 2.1rc1 on 2018-09-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('name', models.TextField(default='atom name')),
                ('color', models.TextField(default='#62A6DA')),
                ('mass', models.FloatField(default=0)),
                ('radius', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(default='cluster')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Atom')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.TextField(default='Wurka')),
                ('details', models.TextField(default='document details')),
                ('name', models.TextField(default='document name')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atom1', to='editor.Atom')),
                ('atom2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atom2', to='editor.Atom')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Document')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Document'),
        ),
        migrations.AddField(
            model_name='atom',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Document'),
        ),
    ]
