# Generated by Django 3.0.2 on 2020-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20190921_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixz',
            name='data',
            field=models.BinaryField(default=b''),
        ),
    ]
