# Generated by Django 2.1rc1 on 2018-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20181116_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixz',
            name='data',
            field=models.BinaryField(default=''),
        ),
    ]
